spring:
  application:
    name: demo
  thymeleaf:
    cache: false
    enabled: true
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    org.apache.shiro: trace