# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Build with Maven
      run: mvn clean package
    - name: Bump version and push tag
      id: bump
      uses: anothrNick/github-tag-action@v1
      env:
        WITH_V: true
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: /target/demo-0.0.1-SNAPSHOT.jar
        tag_name: ${{ steps.bump.outputs.new_tag }}
