# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    tags:
      - "v*"
    branches:
      - master

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Build with Maven
      run: mvn clean package
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: '${{ secrets.MY_TOKEN }}'
        files: /target/demo-0.0.1-SNAPSHOT.jar
        make_latest: "true"
        tag_name: '${{github.ref_name}}'

